remote_theme: "mmistakes/minimal-mistakes@4.16.4"

title: DTS Events
description: The Distributed Text Services (DTS) Specification defines a Hypermedia-Driven Web API for working with collections of text as machine-actionable data.
repository: "distributed-text-services/workshops"
search: true
search_full_content: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

collections:
  events:
    output: true
    permalink: /:collection/:path/

defaults:   
  # _posts
  - scope:
      path: ""
      type: page
    values:
      layout: single
      share: true
      author_profile: false
      related: false
      classes: wide
      sidebar:
        nav: "useful"
  - scope:
      path: "_events"
      type: events
    values:
      layout: single
      share: true
      author_profile: false
      related: false
      sidebar: false
      classes: wide
      sidebar:
        nav: "useful"

bradcrumbs: true
breadcrumb_home_label : "Home"
breadcrumb_separator  : "/"
